version: '3.8'

services:
  # Base de datos MongoDB
  mongodb:
    image: mongo:6.0
    container_name: facturacion-db
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: facturacion123
      MONGO_INITDB_DATABASE: facturacion
    volumes:
      - mongodb_data:/data/db
      - ./mongodb-init:/docker-entrypoint-initdb.d
    networks:
      - facturacion-network

  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: facturacion-backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      NODE_ENV: production
      PORT: 5000
      MONGODB_URI: mongodb://admin:facturacion123@mongodb:27017/facturacion?authSource=admin
      JWT_SECRET: your-super-secure-jwt-secret-key-here-change-this-in-production
      JWT_EXPIRE: 30d
      BCRYPT_ROUNDS: 12
    depends_on:
      - mongodb
    volumes:
      - ./backend/logs:/app/logs
    networks:
      - facturacion-network

  # Frontend React
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: facturacion-frontend
    restart: unless-stopped
    ports:
      - "80:80"
    environment:
      REACT_APP_API_URL: http://localhost:5000
    depends_on:
      - backend
    networks:
      - facturacion-network

volumes:
  mongodb_data:
    driver: local

networks:
  facturacion-network:
    driver: bridge